#!/usr/bin/env python3
#
# 'config-changed'
#
# Runs in several different situations.
#
# * immediately after "install"
# * immediately after "upgrade-charm"
# * at least once when the unit agent is restarted
#   (but, if the unit is in an error state, it won't be run
#   until after the error state is cleared).
# * after changing charm configuration using the GUI or command line interface
#
# It cannot assume that the software has already been started;
# it should not start stopped software, but should (if appropriate)
# restart running software to take configuration changes into account.
#
import setup
setup.pre_install()

from charmhelpers.core import hookenv


def config_changed():
    # Do your act on configuration change
    hookenv.log('Configuration changes', 'INFO')


if __name__ == "__main__":
    config_changed()
