#!/usr/bin/env python3
#
# 'install'
#
# install is run at the beginning of a charm lifecycle.
# The hook should be used to perform one-time setup operations,
# such as installing prerequisite software that will not change
# with configuration changes.
# Like all hooks this must be idempotent because there are scenarios
# where this hook can be run more than once.

import setup
setup.pre_install()

from charmhelpers.core import hookenv


def install():
    
    hookenv.status_set('maintenance', 'Installed, waiting for start')

    hookenv.log('Did some installing', 'INFO')
    
if __name__ == "__main__":
    install()
