#!/usr/bin/env python3
#
# 'install'
#
# install is run at the beginning of a charm lifecycle.
# The hook should be used to perform one-time setup operation.
import setup
import os

#######################################
# Install "charmhelpers" which makes
# charing easier.
#######################################
setup.pre_install()
from charmhelpers.core import hookenv



#######################################
# Run the install procedure
#######################################
def install():

    unitName = os.environ["JUJU_UNIT_NAME"]
    
    hookenv.status_set('maintenance', 'Installed, waiting for start')

    hookenv.log("Ran install for: %s" % unitName, 'INFO')

    
    
if __name__ == "__main__":
    install()
