#!/usr/bin/env python3
#
# 'start'
#
# start runs immediately after the first config-changed hook.
# It should be used to ensure the charm's software is running.
# Note that the charm's software should be configured so as to
# persist through reboots without further intervention on juju's part.

import setup
setup.pre_install()

from charmhelpers.core import hookenv


def start():

    hookenv.status_set('active', 'Started tiny-python')

if __name__ == "__main__":
    start()
