#!/usr/bin/env python3

import setup
setup.pre_install()

from charmhelpers.core import hookenv


def stop():
    hookenv.log('Stopping tiny-python')

    hookenv.status_set('blocked', 'Stopped')

if __name__ == "__main__":
    stop()
