#!/usr/bin/env python3
#
# 'update-status'
#
# Provides constant feedback to the user about the status
# of the service the charm is modeling.
# The charm is run by Juju at regular intervals,
# and gives authors an opportunity to run code that gets
# the “health” of the service or services.

import setup
setup.pre_install()
from charmhelpers.core import hookenv
import datetime

# from os import getloadavg

def update_status():
    now = datetime.datetime.now()
    hookenv.status_set('active', "update-status: {}".format( str( now.strftime("%H:%M") ) ))

if __name__ == "__main__":
    update_status()
