#!/usr/bin/env python3
#
# 'update-status'
#
# Provides constant feedback to the user about the status
# of the service the charm is modeling.
# The charm is run by Juju at regular intervals,
# and gives authors an opportunity to run code that gets
# the “health” of the service or services.

import setup
from os import getloadavg
setup.pre_install()

from charmhelpers.core import hookenv


def update_status():

    hookenv.status_set('active', "Load: {}".format(str(getloadavg())))

if __name__ == "__main__":
    update_status()
