#!/usr/bin/env python3

import setup
setup.pre_install()

from charmhelpers.core import hookenv


def upgrade_charm():
    hookenv.log('Upgrading tiny-python')
    hookenv.status_set('maintenance', 'Upgrading charm')
    # Do some upgrade
    hookenv.status_set('active', 'Upgraded charm')
    

if __name__ == "__main__":
    upgrade_charm()
